[package]
name = "ark-serialize"
description = "A library for serializing types in the arkworks ecosystem"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ark-serialize-derive = { workspace = true, optional = true }
ark-std.workspace = true
digest.workspace = true
num-bigint.workspace = true

[dev-dependencies]
sha2.workspace = true
sha3.workspace = true
blake2.workspace = true
ark-test-curves = { workspace = true, default-features = false, features = [ "bls12_381_curve"] }


[features]
default = []
std = [ "ark-std/std", ]
derive = [ "ark-serialize-derive" ]
