[package]
name = "ark-serialize"
version = "0.4.0-alpha.6"
authors = [ "arkworks contributors" ]
description = "A library for serializing types in the arkworks ecosystem"
homepage = "https://arkworks.rs"
repository = "https://github.com/arkworks-rs/algebra"
documentation = "https://docs.rs/ark-serialize/"
keywords = ["cryptography", "serialization" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.56"

[dependencies]
ark-serialize-derive = { workspace = true, optional = true }
ark-std.workspace = true
digest.workspace = true
num-bigint.workspace = true

[dev-dependencies]
sha2.workspace = true
sha3.workspace = true
blake2.workspace = true
ark-test-curves = { workspace = true, default-features = false, features = [ "bls12_381_curve"] }


[features]
default = []
std = [ "ark-std/std", ]
derive = [ "ark-serialize-derive" ]
